# https://probot.github.io/apps/release-drafter/

name-template: $PREVIOUS_TAG
tag-template: $PREVIOUS_TAG
change-template: $TITLE (#$NUMBER)
categories:
  - title: New Features
    label: enhancement
  - title: Fixed Issues
    label: concern
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
