# https://probot.github.io/apps/stale/

daysUntilStale: 60
daysUntilClose: 30
exemptLabels:
  - concern
  - documentation
  - enhancement
  - help wanted
  - on hold
staleLabel: stale
markComment: >
  Automatically marked as **stale** because there hasn't been any recent activity. It will be closed if no further activity occurs.
closeComment: >
  Automatically **closed** because there hasn't been any activity since this this was marked as stale.