# https://probot.github.io/apps/stale/

daysUntilStale: 60
daysUntilClose: 30
exemptLabels:
  - bug
  - question
  - feature
  - help wanted
  - on hold
staleLabel: stale
markComment: >
  Automatically marked as **stale** because there hasn't been any activity in the last 60 days. If no further activity occurs, this discussion will be closed in 30 days.
closeComment: >
  Automatically **closed** because there hasn't been any activity since this discussion was marked as stale.
