#!/usr/bin/env sh

should_open_shell() {
  case "${1}" in
    -l|--login|-s|--shell) return 0;;
    *) return 1;;
  esac
}

if should_open_shell "${*}"; then
  exec /etc/entrypoint.d/login_shell
else
  exec /etc/entrypoint.d/login_shell "/home/bin/test ${@}"
fi
