name: codecov

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # ./bin/docker build latest
          pwd && ls -la
          ./bin/docker run latest kcov
      - uses: codecov/codecov-action@v1
