name: CI pipeline

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: |
          ./bin/docker build latest
      - name: prepare coverage report
        run: ./bin/docker run latest cp -a /home/coverage /mnt/coverage
      - uses: codecov/codecov-action@v1
