name: codecov

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "REGISTRY_ENDPOINT: ${REGISTRY_ENDPOINT}"
          ./bin/docker build latest
          docker version
          docker image ls
          pwd
          ./bin/docker run latest kcov
      - uses: codecov/codecov-action@v1
